# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  #- 5.6
  - 7.1
  #- hhvm

git:
  depth: 3

before_install:
  #- composer self-update
  #- composer --version

install:
  - composer install

before_script:
  - composer setup-config

script:
  - composer validate --no-interaction
  - composer lint
  - ./vendor/bin/phpcs --standard=./phpcs.xml -n --encoding=utf-8 --extensions=php index.php

after_script: composer test

notifications:
  #- iet-webmaster@open.ac.uk

# End.
